
name: Deno Tests
on:
  workflow_call:

jobs:
  
  tests-deno:
    name: Run Tests with Deno ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [ vx.x.x, v2 ]
    steps:

      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@v3.6.0

      # https://github.com/denoland/setup-deno
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
        with:
          deno-version: ${{ matrix.deno }}
      
      - name: Install Deps
        run: deno install

      - name: Run Tests
        run: deno task test
