
name: Run Tests
on:
  workflow_call:
  push:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.json'
      - '.github/workflows/run-tests.yml'
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.json'
      - '.github/workflows/run-tests.yml'

jobs:
  
  run-tests-node:
    name: Node Tests
    uses: ./.github/workflows/run-tests-node.yml

  run-tests-deno:
    name: Deno Tests
    uses: ./.github/workflows/run-tests-deno.yml
