name: Tests

on: [push]

jobs:
  
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Build package-lock
        run: npm i --package-lock-only
      - name: Clean & Install Deps
        run: npm ci
      - name: Test
        run: npm test
